[package]
name = "types"
version = "0.1.0"
edition = "2018"


[dependencies]
itertools = "0.9"
lexical = "5.2"
# TODO:
small = { git = "https://gitlab.redox-os.org/redox-os/small", features = ["std"] }

