[package]
name = "builitinproc"
version = "0.1.0"
edition = "2018"

[dependencies]
darling = "0.10"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
LibertyShell = { path = "../.." }

[lib]
proc-macro = true

[features]
man = []
